import type { Metadata } from "next";
import { Outfit as SansSerif } from "next/font/google";
import "./globals.css";

const sansSerif = SansSerif({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sansSerif.className} antialiased`}>{children}</body>
    </html>
  );
}
